export const kitchenDesigns = [
  {
    id: 1,
    title: "Modern L-Shaped Kitchen",
    slug: "modern-l-shaped-kitchen",
    category: "L-Shaped Kitchen",
    description: "A space-efficient L-shaped layout with premium matte finish cabinets, integrated lighting, and a functional work triangle.",
    features: ["Soft-close cabinets", "Quartz countertop", "LED under-cabinet lighting", "Built-in storage"],
    price: "Starting at ₹2,50,000",
  },
  {
    id: 2,
    title: "Classic U-Shaped Kitchen",
    slug: "classic-u-shaped-kitchen",
    category: "U-Shaped Kitchen",
    description: "Maximize storage and counter space with this U-shaped design, perfect for larger kitchens with ample workflow.",
    features: ["Corner carousel unit", "Granite countertop", "Chimney provision", "Pull-out drawers"],
    price: "Starting at ₹3,20,000",
  },
  {
    id: 3,
    title: "Minimalist Straight Kitchen",
    slug: "minimalist-straight-kitchen",
    category: "Straight Kitchen",
    description: "A sleek single-wall kitchen design ideal for compact spaces, combining functionality with minimalist aesthetics.",
    features: ["Handle-less cabinets", "Compact appliances", "Space-saving design", "Matte laminate finish"],
    price: "Starting at ₹1,80,000",
  },
  {
    id: 4,
    title: "Elegant Island Kitchen",
    slug: "elegant-island-kitchen",
    category: "Island Kitchen",
    description: "A statement island kitchen with breakfast counter, perfect for open-plan homes and entertaining guests.",
    features: ["Central island with seating", "Waterfall countertop edge", "Premium hardware", "Ambient pendant lighting"],
    price: "Starting at ₹4,50,000",
  },
  {
    id: 5,
    title: "Contemporary Modular Kitchen",
    slug: "contemporary-modular-kitchen",
    category: "Modular Kitchen",
    description: "Fully modular design with maximum customization, blending style with everyday practicality.",
    features: ["Modular cabinet system", "Soft-close hinges", "Customizable layout", "Multiple finish options"],
    price: "Starting at ₹2,90,000",
  },
  {
    id: 6,
    title: "Traditional Wooden Kitchen",
    slug: "traditional-wooden-kitchen",
    category: "Traditional Kitchen",
    description: "Warm, timeless wooden kitchen design combining classic craftsmanship with modern functionality.",
    features: ["Solid wood cabinets", "Traditional hardware", "Warm finish tones", "Ample storage"],
    price: "Starting at ₹3,50,000",
  },
];

export const kitchenCategories = [
  "All",
  "Modular Kitchen",
  "L-Shaped Kitchen",
  "U-Shaped Kitchen",
  "Straight Kitchen",
  "Island Kitchen",
  "Modern Kitchen",
  "Traditional Kitchen",
];

export const projects = [
  {
    id: 1,
    title: "Residential Kitchen Makeover",
    slug: "residential-kitchen-makeover-rs-nagar",
    location: "RS Puram, Coimbatore",
    kitchenType: "L-Shaped Kitchen",
    description: "Complete transformation of an outdated kitchen into a bright, modern cooking space with premium finishes and smart storage solutions.",
    completionDate: "March 2026",
    images: 4,
  },
  {
    id: 2,
    title: "Luxury Villa Kitchen",
    slug: "luxury-villa-kitchen-race-course",
    location: "Race Course, Coimbatore",
    kitchenType: "Island Kitchen",
    description: "A statement island kitchen designed for a luxury villa, featuring premium countertops and an open layout perfect for entertaining.",
    completionDate: "January 2026",
    images: 5,
  },
  {
    id: 3,
    title: "Compact Apartment Kitchen",
    slug: "compact-apartment-kitchen-saibaba-colony",
    location: "Saibaba Colony, Coimbatore",
    kitchenType: "Straight Kitchen",
    description: "Space-optimized straight kitchen design for a compact apartment, maximizing storage without compromising on style.",
    completionDate: "November 2025",
    images: 3,
  },
  {
    id: 4,
    title: "Modern Family Kitchen",
    slug: "modern-family-kitchen-peelamedu",
    location: "Peelamedu, Coimbatore",
    kitchenType: "U-Shaped Kitchen",
    description: "A functional U-shaped kitchen built for a large family, with ample counter space and modern modular cabinetry.",
    completionDate: "September 2025",
    images: 4,
  },
];